plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

apply plugin: 'com.kezong.fat-aar'

android {
    namespace 'io.lantern.sdk'
    ndkVersion "27.0.12077973"
    compileSdkVersion 34
    buildToolsVersion "34.0.0"

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        consumerProguardFiles 'proguard-rules.pro'

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        externalNativeBuild {
            cmake {
                cppFlags ""
                arguments "-DANDROID_STL=c++_shared"
            }
        }

        ndk {
            // Specifies the ABI configurations of native libraries Gradle should build and package with the app.
            abiFilters = ["x86_64", "arm64-v8a"]
            debugSymbolLevel 'FULL'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_22
        targetCompatibility JavaVersion.VERSION_22
        coreLibraryDesugaringEnabled = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/INDEX.LIST'
        exclude 'META-INF/io.netty.versions.properties'
        pickFirst "lib/**/libc++_shared.so"
        jniLibs {
            useLegacyPackaging = true
        }
    }

    buildFeatures {
        compose = false
    }
}



dependencies {

    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.multidex:multidex:2.0.1'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.3'

    embed(name:'lanternsdk-android', ext:'aar')
    
    implementation fileTree(dir: 'libs', include: '*.jar')

    testImplementation 'junit:junit:4.13.2'

    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test:rules:1.6.1'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'com.squareup.okhttp3:okhttp:4.9.2'
}

fataar {
    transitive = false
}

tasks.matching { it.name.startsWith("extractDeepLinks") }.configureEach {
    enabled = false
}

